### ISSUE TITLE
running java program

### ISSUE THREAD

**Issue by GoogleCodeExporter** [downpoured/scite-files#12]
```
What steps will reproduce the problem?
1. >javac root.java


2. 'javac' is not recognized as an internal or external command,
3. operable program or batch file.

W
```

Original issue reported on code.google.com by `sakethin...@gmail.com` on 24 Nov 2014 at 1:35

**Comment by downpoured** [comment]
This behavior is by-design. Either java.properties can specify a path to javac, or javac can be added to the system PATH environment variable.
