### ISSUE TITLE
Oracle extra file missing

### ISSUE THREAD

**Issue by crisistotal2014** [downpoured/scite-files#15]
Hello!
Where are Oracle extra files?

**Comment by downpoured** [comment]
I still see them listed at
https://github.com/downpoured/scite-files/blob/master/files/api_files.md
Search for Oracle on this page, both links work for me.
Please let me know if this answers your question,
-Ben

**Comment by crisistotal2014** [comment]
I saw them. Thank you!
Can you make this files more visible to a novel user? (Now are hard to find).

**Comment by downpoured** [comment]
You're right, they are somewhat difficult to see. I'll be adding more visible links to API files like this within the week.
