### ISSUE TITLE
C.properties malformed

### ISSUE THREAD

**Issue by crisistotal2014** [downpoured/scite-files#16]
Hi!
Can anyone fix 'C.properties? malformed.
Due this "C" language cannot be selected in "Language" menu.
Also Java and another file types lives in this 'C.properties' file and are not selectable.

Thanks in advance!

**Comment by downpoured** [comment]
Hi,
To clarify, are you referring to a C.properties that was downloaded from this website, or one that came with SciTE? Maybe attach the C.properties file to a post here and so I can see what is malformed about it.
-Ben

**Comment by crisistotal2014** [comment]
I'm referring to "C.properties" that came with SciTE.
Seems time ago was done a major modification related to this and I think many files (including sql.properties) were left in a bad running state.

**Comment by arjunae** [comment]
I created the following set, which works out fine for me. 
Of course you will have to adapt some details like file pathing to match your system. 
enjoy...
[c.cpp.js.jq.07.2016.zip](https://github.com/downpoured/scite-files/files/525258/c.cpp.js.jq.07.2016.zip)

**Comment by crisistotal2014** [comment]
Thank so much for your very fast reply. I'll test, but don't worry about paths.

**Comment by crisistotal2014** [comment]
Works like a charm! Please, remember to include in SciTE downloads to help users.

Thank you!

**Comment by crisistotal2014** [comment]
Works like a charm! Please, remember to include in SciTE downloads to help users.

Thank you!

**Comment by crisistotal2014** [comment]
Sorry, but I'm having problems with "Java" source code files: lexer doesn't colourize them with new "*.properties" files.

**Comment by arjunae** [comment]
You may want to choose to try https://eclipse.org/

**Comment by crisistotal2014** [comment]
No, no. I only want SciTE to running as since many years: like a simple and well formed editor.

**Comment by arjunae** [comment]
seems like your lucky.. just found some (old v160) java keywords floatin around and included them. 
[wscite_clike.props.zip](https://github.com/downpoured/scite-files/files/556598/wscite_clike.props.zip)

**Comment by arjunae** [comment]
seems like your lucky.. just found some (old v160) java keywords floatin around and included them. (update)
[wscite_clike.props.zip](https://github.com/downpoured/scite-files/files/557814/wscite_clike.props.zip)

**Comment by crisistotal2014** [comment]
Thank you arjunae! I'll try them.

**Comment by downpoured** [comment]
Thank you for pointing out these links. I'll begin adding the new api files to this project.

**Comment by downpoured** [comment]
Re some of the questions above:
- When adding a new .properties file, make sure it is imported so that the changes take effect.
- The filter.java line looks right to me.
- A new java properties file with updated keywords, (thanks @arjunae) has been uploaded and can be found from https://github.com/downpoured/scite-files/blob/master/files/api_files.md
- The style.cpp.nn lines are not needed for Java, because Java uses the cpp lexer.

**Comment by arjunae** [comment]
...Thanks for clarifying. .. Meanwhile the set recieved css3 keywords and removed dupes..
upped@https://sourceforge.net/projects/scite-webdev/files/?source=navbar
