### ISSUE TITLE
Comment in header of locale.properties

### ISSUE THREAD

**Issue by scootergrisen** [downpoured/scite-files#21]
In the translations files it says:

```
# locale.properties by ...
# Placed in the public domain 2001

# locale.properties defines the localised text for the user interface

```

This makes sense for the file locale.properties.
But for the other translations like locale.da.properties i suppose it should be

```
# locale.da.properties by [translator name] ...
# Placed in the public domain [maybe year of translaton like 2010-2016]

# locale.??.properties defines the localised text for the user interface
```

Perhaps add info on this on translations.md so people know what to do so they can have they name in the translation. And e-mail if they like so maybe its easier for other people to contact them if they want to help out.

**Comment by downpoured** [comment]
Updated the template to encourage people to leave a contact e-mail address.
https://github.com/downpoured/scite-files/commit/a8f0e7b12c1f0d8f433b825e3714f19833ad4c25#diff-58badd7e7ff62206fda922aad7417128

In the last few years it seems like most people have left either a contact email or submitted from a GitHub account, and so it seems like the convention is already being followed.

When the language is installed, it will be renamed to `locale.properties`, so it doesn't seem that out-of-place to me.
