### ISSUE TITLE
Save as dialog does not ask if i want to overwrite existing file

### ISSUE THREAD

**Issue by scootergrisen** [downpoured/scite-files#22]
I accidentally overwrote the wrong file in the Save as dialog.
Should the Save as dialog not ask about overwriting a file that already exists?

**Comment by downpoured** [comment]
I wasn't able to repro the problem, I do get a dialog asking if I'm sure I want to overwrite.

If the problem still occurs for you, I'd suggest contacting the mailing list at 
https://groups.google.com/forum/#!forum/scite-interest
or opening an issue on the official tracker, 
https://sourceforge.net/projects/scintilla/files/SciTE/
