### ISSUE TITLE
missing translation

### ISSUE THREAD

**Issue by Spider-Mann** [downpoured/scite-files#34]
The following message can not be translated:

The file '^0' has been deleted.

Spider-Mann

Edit:
Oh sorry, I'm using Scite 4.0.5.
The message can be generated as follows:
- Open any file
- Minimize scite
- Delete opened file
- Maximize scite
- Message box: The file 'Filename' has been deleted.

**Comment by downpoured** [comment]
Thank you for opening this issue, I am currently on vacation, but will try to look by next week,
-Ben

**Comment by valterbastianelli** [comment]
Other missing strings in 4.0.5:

- Select All Bookmarks
- Selection Add Next
- Selection Add Each
- Reverse Selected Lines

Valter

**Comment by downpoured** [comment]
You're right, Neil's locale.properties on scintilla.org was out of date, I had assumed it would always be the latest.

I contacted Neil yesterday on the mailing list and he uploaded the correct version.

To prevent this from happening again, I'm no longer linking to scintilla.org and will maintain a copy of the latest locale.properties here,
https://raw.githubusercontent.com/downpoured/scite-files/master/files/files/translations/latest/locale.properties
